// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Repository;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240524173842_AddImageUrls")]
    partial class AddImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Entities.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApi.Entities.Models.ImageUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImageUrlId");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImageUrls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e17fb555-4818-4f89-80a5-2a049d2f7cc5"),
                            PublicUrl = "test",
                            Url = "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png"
                        },
                        new
                        {
                            Id = new Guid("01848ecf-26af-4a4d-8cfd-2eff42e407cc"),
                            PublicUrl = "test",
                            Url = "https://www.custommacbd.com/cdn/shop/products/AppleMacBookProwithM2chip2022model_8GB_256GB_CustomMacBD_540x.jpg?v=1659438499"
                        },
                        new
                        {
                            Id = new Guid("9bcaf53b-c304-4b6c-9173-b398bfcee8e9"),
                            PublicUrl = "test",
                            Url = "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg"
                        },
                        new
                        {
                            Id = new Guid("61a515e3-93e4-428d-9458-e345942b9c49"),
                            PublicUrl = "test",
                            Url = "https://adminapi.applegadgetsbd.com/storage/media/large/iPhone-14-Pro-Max-Silver-8456.jpg"
                        },
                        new
                        {
                            Id = new Guid("2757576e-ad5f-4b45-99df-1b055e332cd5"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_TxUk8mcOtG7_mZmNA6TOZZbADyp3L3HHCg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("508d6b5d-c1a4-48aa-9e80-35fce7cf5821"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_TxUk8mcOtG7_mZmNA6TOZZbADyp3L3HHCg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("7ba01de0-3dde-492f-b965-4b38ab3d0d72"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSP2a13umWJp5HCeGtJtw9EuW8opwZfY7r6Q&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("794b89f8-309f-43b6-9dc5-acacf5adf27b"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSP2a13umWJp5HCeGtJtw9EuW8opwZfY7r6Q&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("bea1e1df-86af-4c84-8b23-36a241704671"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSP2a13umWJp5HCeGtJtw9EuW8opwZfY7r6Q&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("fc8d876e-c8fb-4059-91e9-d665935433e4"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdUieJcGTqKDqG2pwd8y0PngaUFR0EvjuqPw&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("a1655193-d279-4e4b-b189-1e399252b36f"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdUieJcGTqKDqG2pwd8y0PngaUFR0EvjuqPw&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("adbb7a13-a1f8-4ca7-bd3e-ae78be4ce6d8"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1eifg73dBnUR8qM29W4H7iXk9NCRskq67KQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("4271c7ac-6bd8-4c60-937e-52ef41c6deda"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1eifg73dBnUR8qM29W4H7iXk9NCRskq67KQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("1877aae0-b790-4812-9874-2b56be800823"),
                            PublicUrl = "test",
                            Url = "https://dlcdnwebimgs.asus.com/gain/0ad9bdfe-9c75-41fb-82f5-6a6bf25bab22/w800"
                        },
                        new
                        {
                            Id = new Guid("7958ffb7-51f4-4b3c-b711-b71674580876"),
                            PublicUrl = "test",
                            Url = "https://dlcdnwebimgs.asus.com/gain/0ad9bdfe-9c75-41fb-82f5-6a6bf25bab22/w800"
                        },
                        new
                        {
                            Id = new Guid("df45dfbf-4f6f-497f-b303-20eb2447269c"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc4HSepwRQjDLQitxc9LHPjdKN-8pYQPGlDA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("185f6eed-fd14-44b3-b76e-3338ec49d203"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc4HSepwRQjDLQitxc9LHPjdKN-8pYQPGlDA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("b5b9504f-ca2a-4956-8bf2-81256d884382"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lvpJRN10N75r-1ssE_0tpl9dvmOEiKQzXQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("4570a650-bc2e-4a22-bdd4-56356db4c4c4"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lvpJRN10N75r-1ssE_0tpl9dvmOEiKQzXQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("34f03c4b-57d2-4982-a7f6-7d1cf1130de7"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvyCDsCiIgME0mgv_vJYB-285xwWl3bC-pSw&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("bdb38aee-0a13-4df8-b7ca-1561d87dedaf"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvyCDsCiIgME0mgv_vJYB-285xwWl3bC-pSw&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("c336faed-515a-4622-866d-246bc3aba711"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwSpfSyrQUCFFTMei2zILF0-xFsIYgNgVVSA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("658caf8f-f8de-4e90-87fb-1b4794c46481"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwSpfSyrQUCFFTMei2zILF0-xFsIYgNgVVSA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("30488fd8-0454-466d-9025-c7b7064ef2c4"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXd2u896WCZISe8VyWsmvOQhwbLREi0O93YQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("fb52a8d1-3f0c-45e6-a12f-b1d49b8152a9"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXd2u896WCZISe8VyWsmvOQhwbLREi0O93YQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("c1439a03-ca5d-42b4-b141-f2ee6933c119"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6AmSV387Vy0EVlO6hYPgsKqPnIA_qxq41oA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("4870fe9d-0d52-41cc-a45f-96c0412f1349"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6AmSV387Vy0EVlO6hYPgsKqPnIA_qxq41oA&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("1f65429d-e22c-436c-9d8d-75faa42998ca"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBOB80TIoBkL_NaeJ_5lG5LuUsD0IYEDXFJg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("6fcda14d-2872-4433-b4bf-fa9b48c475a3"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2zcpFb-6hMeoBVWrfp4LazbLD3a1tEjJjY2oYq45yJOyb28WIIYBoJ3qZMsmFdImBSZk&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("d9a78e8b-3496-4d0d-b185-e99a5a32b4fb"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1GMCvSHthjghTol1tXK_t4eW7Vk-EuBvdnQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("32fe106c-fa5d-4d7a-8b4d-15089584ce23"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1GMCvSHthjghTol1tXK_t4eW7Vk-EuBvdnQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("3f166a0c-c690-475d-b4fd-de4b777d5ccc"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg7XWy1cmt1D3uUjF29eo2q4HgqJaGEu9XDg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("2b36c506-8a20-41e8-8faf-02b1df746104"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg7XWy1cmt1D3uUjF29eo2q4HgqJaGEu9XDg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("5d48f1c9-84d8-42e5-a423-1082e7272832"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCEvcavb1VnIbFqFEh_5sgzYPgjcVAbFLl7g&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("c9ac0af4-c846-4fa0-8f9b-a14349a8528d"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCEvcavb1VnIbFqFEh_5sgzYPgjcVAbFLl7g&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("b7c29ca9-11b3-44ff-b047-84ccb0f1cfa0"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdd3n1bpYxsBGOpZ6ZgUPIKdLVChEegzOBnQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("6ef972d4-12be-4ada-a11a-ae4ba1e578ce"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdd3n1bpYxsBGOpZ6ZgUPIKdLVChEegzOBnQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("dd3d0660-25a2-474b-afd4-85688f23efa3"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR42FePhUrLX424aLie09J4Pfkn03T8h3D7PQ&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("cb32cc3b-45cc-4f4b-8db2-cabfe4337a50"),
                            PublicUrl = "test",
                            Url = "https://www.lenovo.com/medias/lenovo-tablet-p10-2.png?context=bWFzdGVyfHJvb3R8NTI0NzIyfGltYWdlL3BuZ3xoM2IvaDFkLzk4MTA1NjI0ODIyMDYucG5nfDI1OGI3YjlkODNkMzI2OThkOWEwMjM1NjliNjI5ZDQ3ZjMxZTg4ZDQ5ZmE5NGY3NTEyYjMwYTA0NDBlM2VhZDA"
                        },
                        new
                        {
                            Id = new Guid("9e2762dd-cab2-495d-91e1-ef6410bae2aa"),
                            PublicUrl = "test",
                            Url = "https://www.lenovo.com/medias/lenovo-tablet-p10-2.png?context=bWFzdGVyfHJvb3R8NTI0NzIyfGltYWdlL3BuZ3xoM2IvaDFkLzk4MTA1NjI0ODIyMDYucG5nfDI1OGI3YjlkODNkMzI2OThkOWEwMjM1NjliNjI5ZDQ3ZjMxZTg4ZDQ5ZmE5NGY3NTEyYjMwYTA0NDBlM2VhZDA"
                        },
                        new
                        {
                            Id = new Guid("34951477-c4e7-4437-806b-5dd5b24c3518"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoJTwIqCk049REtJbZL5xEYO5W9m6iUiSRSg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("9f7d872b-82a3-423f-b104-a25c71eefbba"),
                            PublicUrl = "test",
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoJTwIqCk049REtJbZL5xEYO5W9m6iUiSRSg&usqp=CAU"
                        },
                        new
                        {
                            Id = new Guid("0fe80206-b480-4c00-a973-cf31c29d7634"),
                            PublicUrl = "test",
                            Url = "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png"
                        },
                        new
                        {
                            Id = new Guid("cdc9d381-c774-4d66-8ca9-6ccc14aa9a74"),
                            PublicUrl = "test",
                            Url = "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png"
                        },
                        new
                        {
                            Id = new Guid("79b09059-7158-47b3-b359-14110d2ff2f0"),
                            PublicUrl = "test",
                            Url = "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1"
                        },
                        new
                        {
                            Id = new Guid("5af7b311-f23c-4300-a30d-2be9a00bfab9"),
                            PublicUrl = "test",
                            Url = "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1"
                        },
                        new
                        {
                            Id = new Guid("b8333f6b-5c83-4d39-aa45-7906456ece77"),
                            PublicUrl = "test",
                            Url = "https://mirzacdns3.s3.ap-south-1.amazonaws.com/cache/catalog/RLV0015/2-800x800.jpg"
                        },
                        new
                        {
                            Id = new Guid("1cb7860f-ff8f-41a4-acd7-fd5fd5699b69"),
                            PublicUrl = "test",
                            Url = "https://mirzacdns3.s3.ap-south-1.amazonaws.com/cache/catalog/RLV0015/2-800x800.jpg"
                        },
                        new
                        {
                            Id = new Guid("20c47ce7-d102-450e-a868-5308cc1061c1"),
                            PublicUrl = "test",
                            Url = "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1"
                        },
                        new
                        {
                            Id = new Guid("eac8aec4-ef9f-415f-9acc-aaf0fec4ddae"),
                            PublicUrl = "test",
                            Url = "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1"
                        },
                        new
                        {
                            Id = new Guid("76082b3c-45ba-410f-b249-279d76d8474f"),
                            PublicUrl = "test",
                            Url = "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg"
                        },
                        new
                        {
                            Id = new Guid("9cbeec46-f118-49c6-980b-a8a054491226"),
                            PublicUrl = "test",
                            Url = "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg"
                        },
                        new
                        {
                            Id = new Guid("d810bd67-3c9a-4502-8d6a-34655761fc1c"),
                            PublicUrl = "test",
                            Url = "https://www.startech.com.bd/image/cache/catalog/headphone/havit/h763d/h763d-02-500x500.jpg"
                        },
                        new
                        {
                            Id = new Guid("e049e6e2-8837-403f-9b0b-f057d76fbb95"),
                            PublicUrl = "test",
                            Url = "https://eratablet.com/wp-content/uploads/2022/08/H51ba6537405f4948972e293927673546u.jpg"
                        },
                        new
                        {
                            Id = new Guid("b41d8b5c-1ce5-4b8d-95b5-32bcfe5a6c37"),
                            PublicUrl = "test",
                            Url = "https://www.bdstall.com/asset/product-image/giant_213181.jpg"
                        },
                        new
                        {
                            Id = new Guid("1d9050ec-7b98-4c25-b797-bddda6af7a4f"),
                            PublicUrl = "test",
                            Url = "https://unixnetworkbd.com/image/cache/wp/gj/unix_network_images/product/gaming-pc-9th-gen-core-i7-9700k/Gaming-PC-9th-Gen-Core-i7-9700k-Unix-Computer-jashore-bangladesh-500x500.webp"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount_Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Total_Sell")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReviewId");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Ratings")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid?>("ShopAvatarsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopAvatarsId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("WebApi.Entities.Models.ShopAvatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopAvatarId");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopAvatars");
                });

            modelBuilder.Entity("WebApi.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Entities.Models.ImageUrl", b =>
                {
                    b.HasOne("WebApi.Entities.Models.Product", null)
                        .WithMany("ImageURLs")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Product", b =>
                {
                    b.HasOne("WebApi.Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Review", b =>
                {
                    b.HasOne("WebApi.Entities.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.HasOne("WebApi.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Shop", b =>
                {
                    b.HasOne("WebApi.Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Models.ShopAvatar", "ShopAvatars")
                        .WithMany()
                        .HasForeignKey("ShopAvatarsId");

                    b.Navigation("Product");

                    b.Navigation("ShopAvatars");
                });

            modelBuilder.Entity("WebApi.Entities.Models.Product", b =>
                {
                    b.Navigation("ImageURLs");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
