//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/7/2024 5:36:32 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Mail;

namespace Model
{
    public partial class Email {

        public Email()
        {
            OnCreated();
        }

        public Guid Id { get; set; }
        public string Body { get; set; } = null!;
        //public ICollection<Attachment>? attachments { get; set; }
        public bool IsBodyHtml { get; set; }
        public MailPriority Priority { get; set; }
        public string Content { get; set; } = null!;
        public string Subject { get; set; } = null!;

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
