//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/7/2024 5:36:32 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class User : IdentityUser
    {

        public User()
        {
            OnCreated();
        }

        public string? FullName { get; set; } = null!;
        public DateTime? Birthday { get; set; }
        public string? Gender { get; set; } = null!;


        public string? Country { get; set; }
        public string? City { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public int? ZipCode { get; set; }        


        public string? ShopDescription { get; set; }

        public string? RefreshToken { get; set; }
        public DateTime? RefreshTokenExpiryTime { get; set; }

        
        public string RoleId { get; set; }
        public ICollection<Role>? Role { get; set; }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
