//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/7/2024 5:36:32 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class Category {

        public Category()
        {
            OnCreated();
        }

        public Guid Id { get; set; }

        public string Title { get; set; } = null!;

        public string SubTitle { get; set; } = null!;

        public string Image_Url { get; set; } = null!;

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
