//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/7/2024 5:36:32 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class Product {

        public Product()
        {
            OnCreated();
        }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int Price { get; set; }

        public int Discount_price { get; set; }

        public int Rating { get; set; }

        public int Total_sell { get; set; }

        public int Stock { get; set; }

        public Guid CategoryId { get; set; }

        public Guid ShopId { get; set; }

        public ICollection<ImageUrl>? Image_Url{ get; set; }
        public ICollection<Review>? Reviews { get; set; }
        public Shop? Shop { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
